<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
    <ApplicationIcon>ico.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ImGui.NET" Version="1.91.6.1" />
    <PackageReference Include="Veldrid" Version="4.9.0" />
    <PackageReference Include="Veldrid.StartupUtilities" Version="4.9.0" />
    <PackageReference Include="Vortice.D3DCompiler" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="vendor\CUE4Parse\CUE4Parse\CUE4Parse.csproj" />
    <ProjectReference Include="vendor\CUE4Parse\CUE4Parse-Conversion\CUE4Parse-Conversion.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="vendor\**\*.cs" />
    <EmbeddedResource Remove="vendor\**\*" />
    <None Remove="vendor\**\*" />
  </ItemGroup>

  <ItemGroup>
    <None Include="utils\oo2core_9_win64.dll" CopyToOutputDirectory="PreserveNewest" />
    <None Include="CUE4Parse-Natives.dll" CopyToOutputDirectory="PreserveNewest" />
    <None Include="BlenderAddons\**\*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="ico.ico" />
    <EmbeddedResource Include="Shaders\GLSL\imgui-vertex.glsl" LogicalName="imgui-vertex.glsl" />
    <EmbeddedResource Include="Shaders\GLSL\imgui-frag.glsl" LogicalName="imgui-frag.glsl" />
    <EmbeddedResource Include="Shaders\HLSL\imgui-vertex.hlsl.bytes" LogicalName="imgui-vertex.hlsl.bytes" />
    <EmbeddedResource Include="Shaders\HLSL\imgui-frag.hlsl.bytes" LogicalName="imgui-frag.hlsl.bytes" />
    <EmbeddedResource Include="Shaders\SPIR-V\imgui-vertex.spv" LogicalName="imgui-vertex.spv" />
    <EmbeddedResource Include="Shaders\SPIR-V\imgui-frag.spv" LogicalName="imgui-frag.spv" />
    <EmbeddedResource Include="Shaders\Metal\imgui-vertex.metallib" LogicalName="imgui-vertex.metallib" />
    <EmbeddedResource Include="Shaders\Metal\imgui-frag.metallib" LogicalName="imgui-frag.metallib" />
  </ItemGroup>
</Project>
